
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND AS BOOL BREAK CASE CDER CIZQ COMA COMILLAD COMILLAS DIGUAL DIV DIVENTERO DOSPUNTOS DOUBLE DRESTA DSUMA DYNAMIC ELSE ELSEIF ENTERO FLECHA FOR FUNCIONARR FUNCIONRANGE FUNCIONSTDIN FUNCIONSTDOUT FUNCIONSTRING FUNCIONTAKE IF IGUAL INT IS ISNEGADO LDER LIST LIZQ MAP MAYIGUAL MAYOR MENIGUAL MENOR MOD MULTI NOIGUAL NOT NUM OR PDER PIZQ PRINT PUNTOYCOMA RESTA RETURN SET STRING SUMA SWITCH VAR VARIABLE WHILEfinal : expresion PUNTOYCOMA\n\n    expresion : valor\n    valor : ENTERO\n             | VARIABLE\n    expresion : valor operadorMat expresionoperadorMat : SUMA\n                   | RESTA\n                   | MULTI\n                   | DIV\n                   | DIVENTERO\n                   | MOD\n    '
    
_lr_action_items = {'ENTERO':([0,7,8,9,10,11,12,13,],[4,4,-6,-7,-8,-9,-10,-11,]),'VARIABLE':([0,7,8,9,10,11,12,13,],[5,5,-6,-7,-8,-9,-10,-11,]),'$end':([1,6,],[0,-1,]),'PUNTOYCOMA':([2,3,4,5,14,],[6,-2,-3,-4,-5,]),'SUMA':([3,4,5,],[8,-3,-4,]),'RESTA':([3,4,5,],[9,-3,-4,]),'MULTI':([3,4,5,],[10,-3,-4,]),'DIV':([3,4,5,],[11,-3,-4,]),'DIVENTERO':([3,4,5,],[12,-3,-4,]),'MOD':([3,4,5,],[13,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'final':([0,],[1,]),'expresion':([0,7,],[2,14,]),'valor':([0,7,],[3,3,]),'operadorMat':([3,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> final","S'",1,None,None,None),
  ('final -> expresion PUNTOYCOMA','final',2,'p_final','sintaxis.py',8),
  ('expresion -> valor','expresion',1,'p_expresion','sintaxis.py',15),
  ('valor -> ENTERO','valor',1,'p_valor','sintaxis.py',19),
  ('valor -> VARIABLE','valor',1,'p_valor','sintaxis.py',20),
  ('expresion -> valor operadorMat expresion','expresion',3,'p_expresion_aritmetica','sintaxis.py',26),
  ('operadorMat -> SUMA','operadorMat',1,'p_operadorMat','sintaxis.py',29),
  ('operadorMat -> RESTA','operadorMat',1,'p_operadorMat','sintaxis.py',30),
  ('operadorMat -> MULTI','operadorMat',1,'p_operadorMat','sintaxis.py',31),
  ('operadorMat -> DIV','operadorMat',1,'p_operadorMat','sintaxis.py',32),
  ('operadorMat -> DIVENTERO','operadorMat',1,'p_operadorMat','sintaxis.py',33),
  ('operadorMat -> MOD','operadorMat',1,'p_operadorMat','sintaxis.py',34),
]
